default:
  tags:
    - cd
    - ci

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Building the application..."
    - mkdir -p build
    - javac -d build src/main/java/*.java src/main/java/*/*.java
    - jar cfe Tsuro.jar main.java.TsuroGame -C build .
  artifacts:
    paths:
      - Tsuro.jar

test:
  stage: test
  script:
    - chmod +x runTests.sh
    - ./runTests.sh
